#!/bin/sh

source ~/.profile
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
MASTER_DIR=`pwd`

CALC_DIR="/scratch/s1333534/sn_beta_phonon"
mkdir -p $CALC_DIR
cd $CALC_DIR

cat > sn.beta.scf.in << EOF
&control
        calculation = 'scf',
        prefix = 'sn.beta',
        tstress = .true.,
/
&system
        ibrav = 0,
        celldm(1) = 11.07803293,
        nat = 2,
        ntyp = 1,
        ecutwfc = 50,
        ecutrho = 400,
        occupations = 'smearing',
        smearing = 'm-v',
        nr1=80,
        nr2=80,
        nr3=80,
        degauss = 0.02,
/
&electrons
        mixing_beta = 0.7,
        conv_thr = 1.0d-10,
/
CELL_PARAMETERS {alat}
 1.000000000   0.000000000   0.000000000
 0.000000000   1.000000000   0.000000000
 0.500000000   0.500000000   0.269532635
ATOMIC_SPECIES
 Sn 118.71 sn_pbe_v1.4.uspp.F.UPF
ATOMIC_POSITIONS crystal
 Sn 0.625000000   0.875000000   0.750000000
 Sn 0.375000000   0.125000000   0.250000000
K_POINTS automatic
 12 12 20       1 1 1
EOF

mpirun -np 4 pw.x < sn.beta.scf.in > sn.beta.scf.out

#Go through the inputs, pairing up the phonons (input like p1start p1end p2start p2end...)

for ((i=1;i<=$#;i=i+2))
do
	j=$((i+1))
	cat > sn.beta.ph.${!i}.${!j}.in << EOF
Beta Tin Phonon Calculation for Lat_Param=11.07803293
&inputph
        prefix = 'sn.beta',
        ldisp = .true.,
        nq1 = 8,
        nq2 = 8,
        nq3 = 8,
	start_q = ${!i},
	last_q = ${!j},
        fildyn = 'sn.beta.dyn',
/
EOF
	mpirun -np 4 ph.x < sn.beta.ph.${!i}.${!j}.in > sn.beta.ph.${!i}.${!j}.out
	cp *.dyn* $MASTER_DIR
done
