#!/bin/sh

cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname

run_no=1

MASTER_DIR=`pwd`
RUN_DIR="$MASTER_DIR/run_$run_no"
SCRATCH_DIR="/scratch/s1333534/sn_alpha_relax/run_$run_no"

mkdir -p $SCRATCH_DIR

cd "$SCRATCH_DIR"

for TARGETPRESSURE in `seq 0 10 0`; do #-1 GPa to 10GPa

	
	cat > sn.alpha.vcrelax.$TARGETPRESSURE.in << EOF
&control 
	calculation = 'vc-relax',
	prefix = 'sn.alpha.relax',
/
&system
	ibrav = 2,
	celldm(1) = 12.52,
	nat = 2,
	ntyp = 1,
	ecutwfc = 50,
	ecutrho = 400,
/
&electrons
	mixing_beta = 0.7,
	conv_thr = 1.0d-10,
/
&IONS
	ion_dynamics = 'bfgs',
/
&CELL
	cell_dynamics = 'bfgs',
	press = $TARGETPRESSURE,
	press_conv_thr = 0.3D0
/
ATOMIC_SPECIES
 Sn 118.71 sn_pbe_v1.4.uspp.F.UPF
ATOMIC_POSITIONS crystal
 Sn 0.0 0.0 0.0
 Sn 0.25 0.25 0.25
K_POINTS automatic
 16 16 16 1 1 1
EOF
	
	mpirun -np 4 pw.x < sn.alpha.vcrelax.$TARGETPRESSURE.in > sn.alpha.vcrelax.$TARGETPRESSURE.out

done;

mkdir -p "$RUN_DIR"
cp *.in *.out "$RUN_DIR"
