#!/bin/sh

cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname

run_no=1

MASTER_DIR=`pwd`
RUN_DIR="$MASTER_DIR/run_$run_no"
SCRATCH_DIR="/scratch/s1333534/sn_alpha_relax/run_$run_no"

mkdir -p $SCRATCH_DIR

cd "$SCRATCH_DIR"

for TARGETPRESSURE in `seq 0 10 0`; do #-1 GPa to 10GPa

	
	cat > sn.alpha.vcrelax.$TARGETPRESSURE.in << EOF
&control 
	calculation = 'vc-relax',
	prefix = 'sn.alpha.relax',
/
&system
	ibrav = 0,
	celldm(1) = 11.23746432,
	nat = 2,
	ntyp = 1,
	ecutwfc = 50,
	ecutrho = 500,
	occupations = 'smearing',
	smearing = 'm-v',
	degauss = 0.02,
	nr1 = 80,
	nr2 = 80,
	nr3 = 80,
/
&electrons
	mixing_beta = 0.7,
	conv_thr = 1.0d-10,
/
&IONS
	ion_dynamics = 'bfgs',
/
&CELL
	cell_dynamics = 'bfgs',
	press = $TARGETPRESSURE,
	press_conv_thr = 0.3D0
/
CELL_PARAMETERS {alat}
0.986 0 0
0 0.986 0
0.493 0.493 0.265
ATOMIC_SPECIES
 Sn 118.71 sn_pbe_v1.4.uspp.F.UPF
ATOMIC_POSITIONS crystal
 Sn 0.625 0.875 0.75
 Sn 0.375 0.125 0.25
K_POINTS automatic
 12 12 20 1 1 1
EOF
	
	mpirun -np 4 pw.x < na.bcc.vcrelax.$TARGETPRESSURE.in > na.bcc.vcrelax.$TARGETPRESSURE.out

done;

mkdir -p "$RUN_DIR"
cp *.in *.out "$RUN_DIR"
